export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_ALL_BOOKS_SUCCESS = "FETCH_ALL_BOOKS_SUCCESS";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const SHOW_BOOK_INPROGRESS = "SHOW_BOOK_INPROGRESS";
