export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS';
export const FETCH_AUTHOR_FAILURE = 'FETCH_AUTHOR_FAILURE';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';
export const CREATE_AUTHOR_FAILURE = 'CREATE_AUTHOR_FAILURE';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE';
export const SHOW_AUTHOR_INPROGRESS = 'SHOW_AUTHOR_INPROGRESS';