export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS";
export const FETCH_ALL_AUTHORS_SUCCESS = "FETCH_ALL_AUTHORS_SUCCESS";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";
export const SHOW_AUTHOR_INPROGRESS = "SHOW_AUTHOR_INPROGRESS";
